
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aamir
 */
public class CalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CalJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
Scanner input=new Scanner(System.in);

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        bclear = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        bproduct = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        bdivide = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bplus = new javax.swing.JButton();
        bminus = new javax.swing.JButton();
        back = new javax.swing.JButton();
        t = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bequal1 = new javax.swing.JButton();
        bpoint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(0, 153, 153));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(0, 161, 156));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        bclear.setBackground(new java.awt.Color(204, 204, 204));
        bclear.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        bclear.setForeground(new java.awt.Color(204, 0, 0));
        bclear.setText("A/C");
        bclear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(204, 204, 204));
        b3.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 153, 153));
        b3.setText("3");
        b3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(204, 204, 204));
        b2.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 153, 153));
        b2.setText("2");
        b2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(204, 204, 204));
        b1.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 153, 153));
        b1.setText("1");
        b1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        bproduct.setBackground(new java.awt.Color(204, 204, 204));
        bproduct.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        bproduct.setForeground(new java.awt.Color(0, 153, 153));
        bproduct.setText("X");
        bproduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bproductActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(204, 204, 204));
        b6.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        b6.setForeground(new java.awt.Color(0, 153, 153));
        b6.setText("6");
        b6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(204, 204, 204));
        b5.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        b5.setForeground(new java.awt.Color(0, 153, 153));
        b5.setText("5");
        b5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(204, 204, 204));
        b4.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 153, 153));
        b4.setText("4");
        b4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        bdivide.setBackground(new java.awt.Color(204, 204, 204));
        bdivide.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        bdivide.setForeground(new java.awt.Color(0, 153, 153));
        bdivide.setText("/");
        bdivide.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bdivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivideActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(204, 204, 204));
        b9.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        b9.setForeground(new java.awt.Color(0, 153, 153));
        b9.setText("9");
        b9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(204, 204, 204));
        b8.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        b8.setForeground(new java.awt.Color(0, 153, 153));
        b8.setText("8");
        b8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(204, 204, 204));
        b7.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        b7.setForeground(new java.awt.Color(0, 153, 153));
        b7.setText("7");
        b7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(204, 204, 204));
        b0.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        b0.setForeground(new java.awt.Color(0, 153, 153));
        b0.setText("0");
        b0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        bplus.setBackground(new java.awt.Color(204, 204, 204));
        bplus.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        bplus.setForeground(new java.awt.Color(0, 153, 153));
        bplus.setText("+");
        bplus.setToolTipText("");
        bplus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bplusActionPerformed(evt);
            }
        });

        bminus.setBackground(new java.awt.Color(204, 204, 204));
        bminus.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        bminus.setForeground(new java.awt.Color(0, 153, 153));
        bminus.setText("-");
        bminus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bminusActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setFont(new java.awt.Font("Square721 Cn BT", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(0, 153, 153));
        back.setText("BkS");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        t.setBackground(new java.awt.Color(0, 102, 102));
        t.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        t.setForeground(new java.awt.Color(255, 255, 255));
        t.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });
        t.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 161, 156));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mine Sticky Calculater 1.0");

        bequal1.setBackground(new java.awt.Color(204, 204, 204));
        bequal1.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        bequal1.setForeground(new java.awt.Color(0, 153, 153));
        bequal1.setText("=");
        bequal1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bequal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bequal1ActionPerformed(evt);
            }
        });

        bpoint.setBackground(new java.awt.Color(204, 204, 204));
        bpoint.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        bpoint.setForeground(new java.awt.Color(0, 153, 153));
        bpoint.setText(".");
        bpoint.setToolTipText("");
        bpoint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpointActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bminus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(bplus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bpoint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bequal1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(bclear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(bproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(bdivide, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bclear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdivide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bminus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bplus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bequal1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        
String n1=null,n2=null;
char op='0';
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
String num1 = b1.getText();
        String a=t.getText();
a=a.concat(num1);
t.setText(a);
        // TODO add your handling code here:
    }                                  

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
String num1 = b3.getText();
String a=t.getText();
a=a.concat(num1);
t.setText(a);        // TODO add your handling code here:
    }                                  

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {                                       
     String a=null;
      t.setText(null);
        // TODO add your handling code here:
    }                                      

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
String num1 = b2.getText();
        String a=t.getText();
a=a.concat(num1);
t.setText(a);        // TODO add your handling code here:
    }                                  

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
String num1 = b4.getText();
        String a=t.getText();
a=a.concat(num1);
t.setText(a);        // TODO add your handling code here:
    }                                  

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
String num1 = b6.getText();
        String a=t.getText();
a=a.concat(num1);
t.setText(a);        // TODO add your handling code here:
    }                                  

    private void bproductActionPerformed(java.awt.event.ActionEvent evt) {                                         
if(n1==null){
        op='*';
        n1=t.getText();
    t.setText(null);
    }
        /*     String num1 = "*";
        String a=t.getText();
a=a.concat(num1);
t.setText(a);*/   // TODO add your handling code here:
    }                                        

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
String num1 = b5.getText();
        String a=t.getText();
a=a.concat(num1);
t.setText(a);        // TODO add your handling code here:
    }                                  

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
String num1 = b7.getText();
        String a=t.getText();
a=a.concat(num1);
t.setText(a);        // TODO add your handling code here:
    }                                  

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {                                   
String num1 = b9.getText();
        String a=t.getText();
a=a.concat(num1);
t.setText(a);        // TODO add your handling code here:
    }                                  

    private void bdivideActionPerformed(java.awt.event.ActionEvent evt) {                                        
if(n1==null){
        op='/';
        n1=t.getText();
    t.setText(null);
    }
        /*    String num1 = bdivide.getText();
        String a=t.getText();
a=a.concat(num1);
t.setText(a);*/    // TODO add your handling code here:
    }                                       

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {                                   
String num1 = b8.getText();
        String a=t.getText();
a=a.concat(num1);
t.setText(a);        // TODO add your handling code here:
    }                                  

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        String num1 = b0.getText();
        String a=t.getText();
        a=a.concat(num1);
        t.setText(a);        // TODO add your handling code here:
    }                                  

    private void bminusActionPerformed(java.awt.event.ActionEvent evt) {                                       
       if(n1==null){
        op='-';
        n1=t.getText();
    t.setText(null);
    }
        /*String num1 = bminus.getText();
        String a=t.getText();
a=a.concat(num1);
t.setText(a);*/        // TODO add your handling code here:
    }                                      

    private void backActionPerformed(java.awt.event.ActionEvent evt) {                                     
String temp=t.getText();
String temp2=bspace(temp);
t.setText(temp2);
        // TODO add your handling code here:
    }                                    

    private void bplusActionPerformed(java.awt.event.ActionEvent evt) {                                      
    if(n1==null){
        op='+';
        n1=t.getText();
    t.setText(null);
    }
/*String num1 = bplus.getText();
String a=t.getText();
a=a.concat(num1);
t.setText(a);*/      // TODO add your handling code here:
    }                                     

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
this.dispose();
        // TODO add your handling code here:
    }                                        
String a;
    private void bequal1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
    if(n1!=null){
        n2=t.getText();
        t.setText(null);
    }if(op!='0'){
    double N1,N2,ans=0;
    N1=Double.parseDouble(n1);
    N2=Double.parseDouble(n2);
    switch(op){
        case '+':
            ans=N1+N2;
            break;
            
        case '-':
            ans=N1-N2;
            break;
            
        case '/':
            ans=N1/N2;
            break;
            
        case '*':
            ans=N1*N2;
            break;
    }
    a=(ans+"");
    t.setText(a);
n1=null;
op='0';}
    // TODO add your handling code here:
    }                                       

    private void bpointActionPerformed(java.awt.event.ActionEvent evt) {                                       
String num1 = bpoint.getText();
String a=t.getText();
if(!a.contains(bpoint.getText()))
a=a.concat(num1);
t.setText(a);        
// TODO add your handling code here:
    }                                      
public String bspace(String s){
    char[] a=s.toCharArray();
    if(s.length()==1)
        return "";
    else{String temp=(a[0]+"");
    for(int i=1;i<(s.length()-1);i++){
        temp=temp.concat(a[i]+"");
    }
    return temp;
    }}
    
    private void tActionPerformed(java.awt.event.ActionEvent evt) {                                  
// TODO add your handling code here:
    }                                 

    private void tKeyTyped(java.awt.event.KeyEvent evt) {                           
char temp=evt.getKeyChar();
if(temp>'9'||temp<'0'){
        String t1=t.getText();
        t1.subSequence(0, t1.length()-100000);
        t.setText(t1);        
    }
// TODO add your handling code here:
    }                          
int posX=0,posY=0;
    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {                                     

// TODO add your handling code here:
    }                                    

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {                                     
    setLocation(evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);        
    // TODO add your handling code here:
    }                                    

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {                                     
posX=evt.getX();
posY=evt.getY();        // TODO add your handling code here:
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton back;
    private javax.swing.JButton bclear;
    private javax.swing.JButton bdivide;
    private javax.swing.JButton bequal1;
    private javax.swing.JButton bminus;
    private javax.swing.JButton bplus;
    private javax.swing.JButton bpoint;
    private javax.swing.JButton bproduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField t;
    // End of variables declaration                   
}
